#!/usr/bin/env bash

if [ "$1" = "-p" ]; then
  PROF=1
  shift
fi

python bench_server.py $1 &
SERVER=$(echo $!)
sleep 1

if [ -n "$PROF" ]; then
  kill -TTIN $SERVER
fi

ab -n100000 -c100 127.0.0.1:8000/

if [ -n "$PROF" ]; then
  kill -TTOU $SERVER
  sleep 1
fi

kill -HUP $SERVER
wait $SERVER
